import type { CardDefinition } from './types';

export const MAGE_CARDS: CardDefinition[] = [
  // ─────────────────────────────────────────────────────────────
  // BASIC CARDS (9 base + 9 upgraded = 18 total)
  // ─────────────────────────────────────────────────────────────

  // Spark
  {
    id: 'm_spark',
    name: 'Spark',
    class: 'mage',
    type: 'attack',
    cost: 1,
    effects: [{ type: 'damage', value: 6, target: 'enemy' }],
    description: 'Deal 6 damage.',
    upgraded: false,
    upgradeId: 'm_spark_plus',
    tier: 'basic',
  },
  {
    id: 'm_spark_plus',
    name: 'Spark+',
    class: 'mage',
    type: 'attack',
    cost: 1,
    effects: [{ type: 'damage', value: 9, target: 'enemy' }],
    description: 'Deal 9 damage.',
    upgraded: true,
    tier: 'basic',
  },

  // Ward
  {
    id: 'm_ward',
    name: 'Ward',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'block', value: 5, target: 'self' }],
    description: 'Gain 5 Block.',
    upgraded: false,
    upgradeId: 'm_ward_plus',
    tier: 'basic',
  },
  {
    id: 'm_ward_plus',
    name: 'Ward+',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'block', value: 8, target: 'self' }],
    description: 'Gain 8 Block.',
    upgraded: true,
    tier: 'basic',
  },

  // Arcane Missile
  {
    id: 'm_arcane_missile',
    name: 'Arcane Missile',
    class: 'mage',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 4, target: 'enemy' },
      { type: 'damage', value: 4, target: 'enemy' },
    ],
    description: 'Deal 4 damage twice.',
    upgraded: false,
    upgradeId: 'm_arcane_missile_plus',
    tier: 'basic',
  },
  {
    id: 'm_arcane_missile_plus',
    name: 'Arcane Missile+',
    class: 'mage',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 6, target: 'enemy' },
      { type: 'damage', value: 6, target: 'enemy' },
    ],
    description: 'Deal 6 damage twice.',
    upgraded: true,
    tier: 'basic',
  },

  // Frost Bolt
  {
    id: 'm_frost_bolt',
    name: 'Frost Bolt',
    class: 'mage',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 7, target: 'enemy' },
      { type: 'debuff', value: 1, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 7 damage. Apply 1 Frozen.',
    upgraded: false,
    upgradeId: 'm_frost_bolt_plus',
    tier: 'basic',
  },
  {
    id: 'm_frost_bolt_plus',
    name: 'Frost Bolt+',
    class: 'mage',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 10, target: 'enemy' },
      { type: 'debuff', value: 1, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 10 damage. Apply 1 Frozen.',
    upgraded: true,
    tier: 'basic',
  },

  // Mana Shield
  {
    id: 'm_mana_shield',
    name: 'Mana Shield',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'block', value: 8, target: 'self' }],
    description: 'Gain 8 Block.',
    upgraded: false,
    upgradeId: 'm_mana_shield_plus',
    tier: 'basic',
  },
  {
    id: 'm_mana_shield_plus',
    name: 'Mana Shield+',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'block', value: 12, target: 'self' }],
    description: 'Gain 12 Block.',
    upgraded: true,
    tier: 'basic',
  },

  // Concentrate
  {
    id: 'm_concentrate',
    name: 'Concentrate',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'energy', value: 1, target: 'self' }],
    description: 'Gain 1 Energy.',
    upgraded: false,
    upgradeId: 'm_concentrate_plus',
    tier: 'basic',
  },
  {
    id: 'm_concentrate_plus',
    name: 'Concentrate+',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'energy', value: 2, target: 'self' }],
    description: 'Gain 2 Energy.',
    upgraded: true,
    tier: 'basic',
  },

  // Focus
  {
    id: 'm_focus',
    name: 'Focus',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'draw', value: 2 }],
    description: 'Draw 2 cards.',
    upgraded: false,
    upgradeId: 'm_focus_plus',
    tier: 'basic',
  },
  {
    id: 'm_focus_plus',
    name: 'Focus+',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'draw', value: 3 }],
    description: 'Draw 3 cards.',
    upgraded: true,
    tier: 'basic',
  },

  // Meditation
  {
    id: 'm_meditation',
    name: 'Meditation',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'heal', value: 4, target: 'self' }],
    description: 'Heal 4 HP.',
    upgraded: false,
    upgradeId: 'm_meditation_plus',
    tier: 'basic',
  },
  {
    id: 'm_meditation_plus',
    name: 'Meditation+',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'heal', value: 7, target: 'self' }],
    description: 'Heal 7 HP.',
    upgraded: true,
    tier: 'basic',
  },

  // Arcane Blast
  {
    id: 'm_arcane_blast',
    name: 'Arcane Blast',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [{ type: 'damage', value: 14, target: 'enemy' }],
    description: 'Deal 14 damage.',
    upgraded: false,
    upgradeId: 'm_arcane_blast_plus',
    tier: 'basic',
  },
  {
    id: 'm_arcane_blast_plus',
    name: 'Arcane Blast+',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [{ type: 'damage', value: 20, target: 'enemy' }],
    description: 'Deal 20 damage.',
    upgraded: true,
    tier: 'basic',
  },

  // ─────────────────────────────────────────────────────────────
  // ELEMENTALIST ARCHETYPE (8 base + 8 upgraded)
  // ─────────────────────────────────────────────────────────────

  // Fireball
  {
    id: 'm_fireball',
    name: 'Fireball',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'aoe_damage', value: 10 },
      { type: 'burn', value: 2, target: 'enemy' },
    ],
    description: 'Deal 10 damage to all enemies. Apply 2 Burn.',
    upgraded: false,
    upgradeId: 'm_fireball_plus',
    archetype: 'elementalist',
    tier: 'common',
  },
  {
    id: 'm_fireball_plus',
    name: 'Fireball+',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'aoe_damage', value: 14 },
      { type: 'burn', value: 3, target: 'enemy' },
    ],
    description: 'Deal 14 damage to all enemies. Apply 3 Burn.',
    upgraded: true,
    archetype: 'elementalist',
    tier: 'common',
  },

  // Blizzard
  {
    id: 'm_blizzard',
    name: 'Blizzard',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'aoe_damage', value: 8 },
      { type: 'debuff', value: 1, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 8 damage to all enemies. Apply 1 Frozen.',
    upgraded: false,
    upgradeId: 'm_blizzard_plus',
    archetype: 'elementalist',
    tier: 'common',
  },
  {
    id: 'm_blizzard_plus',
    name: 'Blizzard+',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'aoe_damage', value: 12 },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 12 damage to all enemies. Apply 2 Frozen.',
    upgraded: true,
    archetype: 'elementalist',
    tier: 'common',
  },

  // Chain Lightning
  {
    id: 'm_chain_lightning',
    name: 'Chain Lightning',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 8, target: 'enemy' },
      { type: 'aoe_damage', value: 4 },
    ],
    description: 'Deal 8 damage to an enemy and 4 damage to all others.',
    upgraded: false,
    upgradeId: 'm_chain_lightning_plus',
    archetype: 'elementalist',
    tier: 'common',
  },
  {
    id: 'm_chain_lightning_plus',
    name: 'Chain Lightning+',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 12, target: 'enemy' },
      { type: 'aoe_damage', value: 6 },
    ],
    description: 'Deal 12 damage to an enemy and 6 damage to all others.',
    upgraded: true,
    archetype: 'elementalist',
    tier: 'common',
  },

  // Ignite
  {
    id: 'm_ignite',
    name: 'Ignite',
    class: 'mage',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 5, target: 'enemy' },
      { type: 'burn', value: 3, target: 'enemy' },
    ],
    description: 'Deal 5 damage. Apply 3 Burn.',
    upgraded: false,
    upgradeId: 'm_ignite_plus',
    archetype: 'elementalist',
    tier: 'common',
  },
  {
    id: 'm_ignite_plus',
    name: 'Ignite+',
    class: 'mage',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 8, target: 'enemy' },
      { type: 'burn', value: 5, target: 'enemy' },
    ],
    description: 'Deal 8 damage. Apply 5 Burn.',
    upgraded: true,
    archetype: 'elementalist',
    tier: 'common',
  },

  // Frost Nova
  {
    id: 'm_frost_nova',
    name: 'Frost Nova',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'aoe_damage', value: 3 },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 3 damage to all enemies. Apply 2 Frozen.',
    upgraded: false,
    upgradeId: 'm_frost_nova_plus',
    archetype: 'elementalist',
    tier: 'common',
  },
  {
    id: 'm_frost_nova_plus',
    name: 'Frost Nova+',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'aoe_damage', value: 5 },
      { type: 'debuff', value: 3, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 5 damage to all enemies. Apply 3 Frozen.',
    upgraded: true,
    archetype: 'elementalist',
    tier: 'common',
  },

  // Meteor
  {
    id: 'm_meteor',
    name: 'Meteor',
    class: 'mage',
    type: 'attack',
    cost: 3,
    effects: [
      { type: 'aoe_damage', value: 18 },
      { type: 'burn', value: 4, target: 'enemy' },
    ],
    description: 'Deal 18 damage to all enemies. Apply 4 Burn.',
    upgraded: false,
    upgradeId: 'm_meteor_plus',
    archetype: 'elementalist',
    tier: 'powerful',
  },
  {
    id: 'm_meteor_plus',
    name: 'Meteor+',
    class: 'mage',
    type: 'attack',
    cost: 3,
    effects: [
      { type: 'aoe_damage', value: 24 },
      { type: 'burn', value: 6, target: 'enemy' },
    ],
    description: 'Deal 24 damage to all enemies. Apply 6 Burn.',
    upgraded: true,
    archetype: 'elementalist',
    tier: 'powerful',
  },

  // Combustion
  {
    id: 'm_combustion',
    name: 'Combustion',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 10, target: 'enemy' },
      { type: 'burn', value: 2, target: 'enemy' },
      { type: 'aoe_damage', value: 4 },
    ],
    description: 'Deal 10 damage. Apply 2 Burn. Deal 4 damage to all enemies.',
    upgraded: false,
    upgradeId: 'm_combustion_plus',
    archetype: 'elementalist',
    tier: 'common',
  },
  {
    id: 'm_combustion_plus',
    name: 'Combustion+',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 14, target: 'enemy' },
      { type: 'burn', value: 3, target: 'enemy' },
      { type: 'aoe_damage', value: 6 },
    ],
    description: 'Deal 14 damage. Apply 3 Burn. Deal 6 damage to all enemies.',
    upgraded: true,
    archetype: 'elementalist',
    tier: 'common',
  },

  // Elemental Surge
  {
    id: 'm_elemental_surge',
    name: 'Elemental Surge',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'aoe_damage', value: 8 },
      { type: 'burn', value: 2, target: 'enemy' },
      { type: 'debuff', value: 1, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 8 damage to all enemies. Apply 2 Burn and 1 Frozen.',
    upgraded: false,
    upgradeId: 'm_elemental_surge_plus',
    archetype: 'elementalist',
    tier: 'powerful',
  },
  {
    id: 'm_elemental_surge_plus',
    name: 'Elemental Surge+',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'aoe_damage', value: 12 },
      { type: 'burn', value: 3, target: 'enemy' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 12 damage to all enemies. Apply 3 Burn and 2 Frozen.',
    upgraded: true,
    archetype: 'elementalist',
    tier: 'powerful',
  },

  // ─────────────────────────────────────────────────────────────
  // ARCANIST ARCHETYPE (8 base + 8 upgraded)
  // ─────────────────────────────────────────────────────────────

  // Siphon Power
  {
    id: 'm_siphon_power',
    name: 'Siphon Power',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'draw', value: 1 },
      { type: 'energy', value: 1, target: 'self' },
    ],
    description: 'Draw 1 card. Gain 1 Energy.',
    upgraded: false,
    upgradeId: 'm_siphon_power_plus',
    archetype: 'arcanist',
    tier: 'common',
  },
  {
    id: 'm_siphon_power_plus',
    name: 'Siphon Power+',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'draw', value: 2 },
      { type: 'energy', value: 1, target: 'self' },
    ],
    description: 'Draw 2 cards. Gain 1 Energy.',
    upgraded: true,
    archetype: 'arcanist',
    tier: 'common',
  },

  // Spell Echo
  {
    id: 'm_spell_echo',
    name: 'Spell Echo',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'draw', value: 2 }],
    description: 'Draw 2 cards.',
    upgraded: false,
    upgradeId: 'm_spell_echo_plus',
    archetype: 'arcanist',
    tier: 'common',
  },
  {
    id: 'm_spell_echo_plus',
    name: 'Spell Echo+',
    class: 'mage',
    type: 'skill',
    cost: 0,
    effects: [{ type: 'draw', value: 2 }],
    description: 'Draw 2 cards.',
    upgraded: true,
    archetype: 'arcanist',
    tier: 'common',
  },

  // Arcane Intellect
  {
    id: 'm_arcane_intellect',
    name: 'Arcane Intellect',
    class: 'mage',
    type: 'skill',
    cost: 2,
    effects: [{ type: 'draw', value: 3 }],
    description: 'Draw 3 cards.',
    upgraded: false,
    upgradeId: 'm_arcane_intellect_plus',
    archetype: 'arcanist',
    tier: 'common',
  },
  {
    id: 'm_arcane_intellect_plus',
    name: 'Arcane Intellect+',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'draw', value: 3 }],
    description: 'Draw 3 cards.',
    upgraded: true,
    archetype: 'arcanist',
    tier: 'common',
  },

  // Time Warp
  {
    id: 'm_time_warp',
    name: 'Time Warp',
    class: 'mage',
    type: 'skill',
    cost: 3,
    effects: [
      { type: 'energy', value: 3, target: 'self' },
      { type: 'draw', value: 2 },
    ],
    description: 'Gain 3 Energy. Draw 2 cards.',
    upgraded: false,
    upgradeId: 'm_time_warp_plus',
    archetype: 'arcanist',
    tier: 'powerful',
  },
  {
    id: 'm_time_warp_plus',
    name: 'Time Warp+',
    class: 'mage',
    type: 'skill',
    cost: 2,
    effects: [
      { type: 'energy', value: 3, target: 'self' },
      { type: 'draw', value: 3 },
    ],
    description: 'Gain 3 Energy. Draw 3 cards.',
    upgraded: true,
    archetype: 'arcanist',
    tier: 'powerful',
  },

  // Mana Surge
  {
    id: 'm_mana_surge',
    name: 'Mana Surge',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'energy', value: 2, target: 'self' }],
    description: 'Gain 2 Energy.',
    upgraded: false,
    upgradeId: 'm_mana_surge_plus',
    archetype: 'arcanist',
    tier: 'common',
  },
  {
    id: 'm_mana_surge_plus',
    name: 'Mana Surge+',
    class: 'mage',
    type: 'skill',
    cost: 0,
    effects: [{ type: 'energy', value: 2, target: 'self' }],
    description: 'Gain 2 Energy.',
    upgraded: true,
    archetype: 'arcanist',
    tier: 'common',
  },

  // Recycle
  {
    id: 'm_recycle',
    name: 'Recycle',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'draw', value: 1 }],
    description: 'Draw 1 card.',
    upgraded: false,
    upgradeId: 'm_recycle_plus',
    archetype: 'arcanist',
    tier: 'common',
  },
  {
    id: 'm_recycle_plus',
    name: 'Recycle+',
    class: 'mage',
    type: 'skill',
    cost: 0,
    effects: [{ type: 'draw', value: 1 }],
    description: 'Draw 1 card.',
    upgraded: true,
    archetype: 'arcanist',
    tier: 'common',
  },

  // Duplicate
  {
    id: 'm_duplicate',
    name: 'Duplicate',
    class: 'mage',
    type: 'skill',
    cost: 2,
    effects: [
      { type: 'draw', value: 2 },
      { type: 'energy', value: 1, target: 'self' },
    ],
    description: 'Draw 2 cards. Gain 1 Energy.',
    upgraded: false,
    upgradeId: 'm_duplicate_plus',
    archetype: 'arcanist',
    tier: 'powerful',
  },
  {
    id: 'm_duplicate_plus',
    name: 'Duplicate+',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'draw', value: 3 },
      { type: 'energy', value: 1, target: 'self' },
    ],
    description: 'Draw 3 cards. Gain 1 Energy.',
    upgraded: true,
    archetype: 'arcanist',
    tier: 'powerful',
  },

  // Overcharge
  {
    id: 'm_overcharge',
    name: 'Overcharge',
    class: 'mage',
    type: 'skill',
    cost: 2,
    effects: [{ type: 'energy', value: 3, target: 'self' }],
    description: 'Gain 3 Energy.',
    upgraded: false,
    upgradeId: 'm_overcharge_plus',
    archetype: 'arcanist',
    tier: 'powerful',
  },
  {
    id: 'm_overcharge_plus',
    name: 'Overcharge+',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'energy', value: 3, target: 'self' }],
    description: 'Gain 3 Energy.',
    upgraded: true,
    archetype: 'arcanist',
    tier: 'powerful',
  },

  // ─────────────────────────────────────────────────────────────
  // FROST MAGE ARCHETYPE (8 base + 8 upgraded)
  // ─────────────────────────────────────────────────────────────

  // Deep Freeze
  {
    id: 'm_deep_freeze',
    name: 'Deep Freeze',
    class: 'mage',
    type: 'skill',
    cost: 2,
    effects: [{ type: 'debuff', value: 3, target: 'enemy', buff: 'frozen' }],
    description: 'Apply 3 Frozen.',
    upgraded: false,
    upgradeId: 'm_deep_freeze_plus',
    archetype: 'frost_mage',
    tier: 'common',
  },
  {
    id: 'm_deep_freeze_plus',
    name: 'Deep Freeze+',
    class: 'mage',
    type: 'skill',
    cost: 2,
    effects: [{ type: 'debuff', value: 5, target: 'enemy', buff: 'frozen' }],
    description: 'Apply 5 Frozen.',
    upgraded: true,
    archetype: 'frost_mage',
    tier: 'common',
  },

  // Ice Barrier
  {
    id: 'm_ice_barrier',
    name: 'Ice Barrier',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 10, target: 'self' },
      { type: 'debuff', value: 1, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Gain 10 Block. Apply 1 Frozen.',
    upgraded: false,
    upgradeId: 'm_ice_barrier_plus',
    archetype: 'frost_mage',
    tier: 'common',
  },
  {
    id: 'm_ice_barrier_plus',
    name: 'Ice Barrier+',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 14, target: 'self' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Gain 14 Block. Apply 2 Frozen.',
    upgraded: true,
    archetype: 'frost_mage',
    tier: 'common',
  },

  // Glacial Spike
  {
    id: 'm_glacial_spike',
    name: 'Glacial Spike',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 12, target: 'enemy' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 12 damage. Apply 2 Frozen.',
    upgraded: false,
    upgradeId: 'm_glacial_spike_plus',
    archetype: 'frost_mage',
    tier: 'common',
  },
  {
    id: 'm_glacial_spike_plus',
    name: 'Glacial Spike+',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 16, target: 'enemy' },
      { type: 'debuff', value: 3, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 16 damage. Apply 3 Frozen.',
    upgraded: true,
    archetype: 'frost_mage',
    tier: 'common',
  },

  // Frostbite
  {
    id: 'm_frostbite',
    name: 'Frostbite',
    class: 'mage',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 6, target: 'enemy' },
      { type: 'debuff', value: 1, target: 'enemy', buff: 'weak' },
      { type: 'debuff', value: 1, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 6 damage. Apply 1 Weak and 1 Frozen.',
    upgraded: false,
    upgradeId: 'm_frostbite_plus',
    archetype: 'frost_mage',
    tier: 'common',
  },
  {
    id: 'm_frostbite_plus',
    name: 'Frostbite+',
    class: 'mage',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 9, target: 'enemy' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'weak' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 9 damage. Apply 2 Weak and 2 Frozen.',
    upgraded: true,
    archetype: 'frost_mage',
    tier: 'common',
  },

  // Shatter
  {
    id: 'm_shatter',
    name: 'Shatter',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 15, target: 'enemy' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Deal 15 damage. Apply 2 Vulnerable.',
    upgraded: false,
    upgradeId: 'm_shatter_plus',
    archetype: 'frost_mage',
    tier: 'common',
  },
  {
    id: 'm_shatter_plus',
    name: 'Shatter+',
    class: 'mage',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 20, target: 'enemy' },
      { type: 'debuff', value: 3, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Deal 20 damage. Apply 3 Vulnerable.',
    upgraded: true,
    archetype: 'frost_mage',
    tier: 'common',
  },

  // Chill
  {
    id: 'm_chill',
    name: 'Chill',
    class: 'mage',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'debuff', value: 2, target: 'enemy', buff: 'frozen' }],
    description: 'Apply 2 Frozen.',
    upgraded: false,
    upgradeId: 'm_chill_plus',
    archetype: 'frost_mage',
    tier: 'common',
  },
  {
    id: 'm_chill_plus',
    name: 'Chill+',
    class: 'mage',
    type: 'skill',
    cost: 0,
    effects: [{ type: 'debuff', value: 2, target: 'enemy', buff: 'frozen' }],
    description: 'Apply 2 Frozen.',
    upgraded: true,
    archetype: 'frost_mage',
    tier: 'common',
  },

  // Frozen Armor
  {
    id: 'm_frozen_armor',
    name: 'Frozen Armor',
    class: 'mage',
    type: 'skill',
    cost: 2,
    effects: [
      { type: 'block', value: 12, target: 'self' },
      { type: 'buff', value: 2, target: 'self', buff: 'thorns' },
      { type: 'debuff', value: 1, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Gain 12 Block and 2 Thorns. Apply 1 Frozen.',
    upgraded: false,
    upgradeId: 'm_frozen_armor_plus',
    archetype: 'frost_mage',
    tier: 'powerful',
  },
  {
    id: 'm_frozen_armor_plus',
    name: 'Frozen Armor+',
    class: 'mage',
    type: 'skill',
    cost: 2,
    effects: [
      { type: 'block', value: 16, target: 'self' },
      { type: 'buff', value: 3, target: 'self', buff: 'thorns' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Gain 16 Block and 3 Thorns. Apply 2 Frozen.',
    upgraded: true,
    archetype: 'frost_mage',
    tier: 'powerful',
  },

  // Absolute Zero
  {
    id: 'm_absolute_zero',
    name: 'Absolute Zero',
    class: 'mage',
    type: 'attack',
    cost: 3,
    effects: [
      { type: 'aoe_damage', value: 14 },
      { type: 'debuff', value: 4, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 14 damage to all enemies. Apply 4 Frozen.',
    upgraded: false,
    upgradeId: 'm_absolute_zero_plus',
    archetype: 'frost_mage',
    tier: 'powerful',
  },
  {
    id: 'm_absolute_zero_plus',
    name: 'Absolute Zero+',
    class: 'mage',
    type: 'attack',
    cost: 3,
    effects: [
      { type: 'aoe_damage', value: 20 },
      { type: 'debuff', value: 6, target: 'enemy', buff: 'frozen' },
    ],
    description: 'Deal 20 damage to all enemies. Apply 6 Frozen.',
    upgraded: true,
    archetype: 'frost_mage',
    tier: 'powerful',
  },
];
