import type { CardDefinition } from './types';

export const ROGUE_CARDS: CardDefinition[] = [
  // ─────────────────────────────────────────────────────────────
  // BASIC STARTER CARDS (9 cards, no archetype, tier: 'basic')
  // ─────────────────────────────────────────────────────────────

  // Stab
  {
    id: 'r_stab',
    name: 'Stab',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [{ type: 'damage', value: 6, target: 'enemy' }],
    description: 'Deal 6 damage.',
    upgraded: false,
    upgradeId: 'r_stab_plus',
    tier: 'basic',
  },
  {
    id: 'r_stab_plus',
    name: 'Stab+',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [{ type: 'damage', value: 9, target: 'enemy' }],
    description: 'Deal 9 damage.',
    upgraded: true,
    upgradeId: 'r_stab',
    tier: 'basic',
  },

  // Dodge
  {
    id: 'r_dodge',
    name: 'Dodge',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'block', value: 5, target: 'self' }],
    description: 'Gain 5 Block.',
    upgraded: false,
    upgradeId: 'r_dodge_plus',
    tier: 'basic',
  },
  {
    id: 'r_dodge_plus',
    name: 'Dodge+',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'block', value: 8, target: 'self' }],
    description: 'Gain 8 Block.',
    upgraded: true,
    upgradeId: 'r_dodge',
    tier: 'basic',
  },

  // Quick Slash
  {
    id: 'r_quick_slash',
    name: 'Quick Slash',
    class: 'rogue',
    type: 'attack',
    cost: 0,
    effects: [{ type: 'damage', value: 4, target: 'enemy' }],
    description: 'Deal 4 damage.',
    upgraded: false,
    upgradeId: 'r_quick_slash_plus',
    tier: 'basic',
  },
  {
    id: 'r_quick_slash_plus',
    name: 'Quick Slash+',
    class: 'rogue',
    type: 'attack',
    cost: 0,
    effects: [{ type: 'damage', value: 7, target: 'enemy' }],
    description: 'Deal 7 damage.',
    upgraded: true,
    upgradeId: 'r_quick_slash',
    tier: 'basic',
  },

  // Backstab
  {
    id: 'r_backstab',
    name: 'Backstab',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [{ type: 'damage', value: 11, target: 'enemy' }],
    description: 'Deal 11 damage.',
    upgraded: false,
    upgradeId: 'r_backstab_plus',
    tier: 'basic',
  },
  {
    id: 'r_backstab_plus',
    name: 'Backstab+',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [{ type: 'damage', value: 16, target: 'enemy' }],
    description: 'Deal 16 damage.',
    upgraded: true,
    upgradeId: 'r_backstab',
    tier: 'basic',
  },

  // Smoke Bomb
  {
    id: 'r_smoke_bomb',
    name: 'Smoke Bomb',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 6, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 6 Block. Draw 1 card.',
    upgraded: false,
    upgradeId: 'r_smoke_bomb_plus',
    tier: 'basic',
  },
  {
    id: 'r_smoke_bomb_plus',
    name: 'Smoke Bomb+',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 9, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 9 Block. Draw 1 card.',
    upgraded: true,
    upgradeId: 'r_smoke_bomb',
    tier: 'basic',
  },

  // Preparation
  {
    id: 'r_preparation',
    name: 'Preparation',
    class: 'rogue',
    type: 'skill',
    cost: 0,
    effects: [{ type: 'draw', value: 2 }],
    description: 'Draw 2 cards.',
    upgraded: false,
    upgradeId: 'r_preparation_plus',
    tier: 'basic',
  },
  {
    id: 'r_preparation_plus',
    name: 'Preparation+',
    class: 'rogue',
    type: 'skill',
    cost: 0,
    effects: [{ type: 'draw', value: 3 }],
    description: 'Draw 3 cards.',
    upgraded: true,
    upgradeId: 'r_preparation',
    tier: 'basic',
  },

  // Fan of Knives
  {
    id: 'r_fan_of_knives',
    name: 'Fan of Knives',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'aoe_damage', value: 5 },
      { type: 'poison', value: 2, target: 'enemy' },
    ],
    description: 'Deal 5 damage to all enemies. Apply 2 Poison.',
    upgraded: false,
    upgradeId: 'r_fan_of_knives_plus',
    tier: 'basic',
  },
  {
    id: 'r_fan_of_knives_plus',
    name: 'Fan of Knives+',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'aoe_damage', value: 7 },
      { type: 'poison', value: 3, target: 'enemy' },
    ],
    description: 'Deal 7 damage to all enemies. Apply 3 Poison.',
    upgraded: true,
    upgradeId: 'r_fan_of_knives',
    tier: 'basic',
  },

  // Evade
  {
    id: 'r_evade',
    name: 'Evade',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'block', value: 8, target: 'self' }],
    description: 'Gain 8 Block.',
    upgraded: false,
    upgradeId: 'r_evade_plus',
    tier: 'basic',
  },
  {
    id: 'r_evade_plus',
    name: 'Evade+',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'block', value: 12, target: 'self' }],
    description: 'Gain 12 Block.',
    upgraded: true,
    upgradeId: 'r_evade',
    tier: 'basic',
  },

  // Shadow Step
  {
    id: 'r_shadow_step',
    name: 'Shadow Step',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'energy', value: 1, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 1 Energy. Draw 1 card.',
    upgraded: false,
    upgradeId: 'r_shadow_step_plus',
    tier: 'basic',
  },
  {
    id: 'r_shadow_step_plus',
    name: 'Shadow Step+',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'energy', value: 1, target: 'self' },
      { type: 'draw', value: 2 },
    ],
    description: 'Gain 1 Energy. Draw 2 cards.',
    upgraded: true,
    upgradeId: 'r_shadow_step',
    tier: 'basic',
  },

  // ─────────────────────────────────────────────────────────────
  // ASSASSIN ARCHETYPE CARDS (8 base + 8 upgraded)
  // Combo chains — cards that build and spend Combo stacks
  // ─────────────────────────────────────────────────────────────

  // Flurry
  {
    id: 'r_flurry',
    name: 'Flurry',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 4, target: 'enemy' },
      { type: 'buff', value: 1, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 4 damage. Gain 1 Combo.',
    upgraded: false,
    upgradeId: 'r_flurry_plus',
    archetype: 'assassin',
    tier: 'common',
  },
  {
    id: 'r_flurry_plus',
    name: 'Flurry+',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 6, target: 'enemy' },
      { type: 'buff', value: 2, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 6 damage. Gain 2 Combo.',
    upgraded: true,
    upgradeId: 'r_flurry',
    archetype: 'assassin',
    tier: 'common',
  },

  // Death Mark
  {
    id: 'r_death_mark',
    name: 'Death Mark',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'debuff', value: 1, target: 'enemy', buff: 'vulnerable' },
      { type: 'buff', value: 1, target: 'self', buff: 'combo' },
    ],
    description: 'Apply 1 Vulnerable. Gain 1 Combo.',
    upgraded: false,
    upgradeId: 'r_death_mark_plus',
    archetype: 'assassin',
    tier: 'common',
  },
  {
    id: 'r_death_mark_plus',
    name: 'Death Mark+',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'debuff', value: 2, target: 'enemy', buff: 'vulnerable' },
      { type: 'buff', value: 2, target: 'self', buff: 'combo' },
    ],
    description: 'Apply 2 Vulnerable. Gain 2 Combo.',
    upgraded: true,
    upgradeId: 'r_death_mark',
    archetype: 'assassin',
    tier: 'common',
  },

  // Execute
  {
    id: 'r_execute',
    name: 'Execute',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 3, target: 'enemy', condition: 'per_combo' },
    ],
    description: 'Deal 3 damage for each Combo you have.',
    upgraded: false,
    upgradeId: 'r_execute_plus',
    archetype: 'assassin',
    tier: 'common',
  },
  {
    id: 'r_execute_plus',
    name: 'Execute+',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 5, target: 'enemy', condition: 'per_combo' },
    ],
    description: 'Deal 5 damage for each Combo you have.',
    upgraded: true,
    upgradeId: 'r_execute',
    archetype: 'assassin',
    tier: 'common',
  },

  // Combo Strike
  {
    id: 'r_combo_strike',
    name: 'Combo Strike',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 5, target: 'enemy' },
      { type: 'buff', value: 1, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 5 damage. Gain 1 Combo.',
    upgraded: false,
    upgradeId: 'r_combo_strike_plus',
    archetype: 'assassin',
    tier: 'common',
  },
  {
    id: 'r_combo_strike_plus',
    name: 'Combo Strike+',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 8, target: 'enemy' },
      { type: 'buff', value: 1, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 8 damage. Gain 1 Combo.',
    upgraded: true,
    upgradeId: 'r_combo_strike',
    archetype: 'assassin',
    tier: 'common',
  },

  // Finishing Blow
  {
    id: 'r_finishing_blow',
    name: 'Finishing Blow',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 14, target: 'enemy' },
      { type: 'buff', value: 1, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 14 damage. Gain 1 Combo.',
    upgraded: false,
    upgradeId: 'r_finishing_blow_plus',
    archetype: 'assassin',
    tier: 'powerful',
  },
  {
    id: 'r_finishing_blow_plus',
    name: 'Finishing Blow+',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 20, target: 'enemy' },
      { type: 'buff', value: 1, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 20 damage. Gain 1 Combo.',
    upgraded: true,
    upgradeId: 'r_finishing_blow',
    archetype: 'assassin',
    tier: 'powerful',
  },

  // Ambush
  {
    id: 'r_ambush',
    name: 'Ambush',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 8, target: 'enemy' },
      { type: 'buff', value: 2, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 8 damage. Gain 2 Combo.',
    upgraded: false,
    upgradeId: 'r_ambush_plus',
    archetype: 'assassin',
    tier: 'common',
  },
  {
    id: 'r_ambush_plus',
    name: 'Ambush+',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 12, target: 'enemy' },
      { type: 'buff', value: 3, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 12 damage. Gain 3 Combo.',
    upgraded: true,
    upgradeId: 'r_ambush',
    archetype: 'assassin',
    tier: 'common',
  },

  // Coup de Grace
  {
    id: 'r_coup_de_grace',
    name: 'Coup de Grace',
    class: 'rogue',
    type: 'attack',
    cost: 3,
    effects: [
      { type: 'damage', value: 4, target: 'enemy', condition: 'per_combo' },
      { type: 'buff', value: 1, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 4 damage per Combo. Gain 1 Combo.',
    upgraded: false,
    upgradeId: 'r_coup_de_grace_plus',
    archetype: 'assassin',
    tier: 'powerful',
  },
  {
    id: 'r_coup_de_grace_plus',
    name: 'Coup de Grace+',
    class: 'rogue',
    type: 'attack',
    cost: 3,
    effects: [
      { type: 'damage', value: 6, target: 'enemy', condition: 'per_combo' },
      { type: 'buff', value: 2, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 6 damage per Combo. Gain 2 Combo.',
    upgraded: true,
    upgradeId: 'r_coup_de_grace',
    archetype: 'assassin',
    tier: 'powerful',
  },

  // Chain Kill
  {
    id: 'r_chain_kill',
    name: 'Chain Kill',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 10, target: 'enemy' },
      { type: 'buff', value: 3, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 10 damage. Gain 3 Combo.',
    upgraded: false,
    upgradeId: 'r_chain_kill_plus',
    archetype: 'assassin',
    tier: 'powerful',
  },
  {
    id: 'r_chain_kill_plus',
    name: 'Chain Kill+',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 15, target: 'enemy' },
      { type: 'buff', value: 4, target: 'self', buff: 'combo' },
    ],
    description: 'Deal 15 damage. Gain 4 Combo.',
    upgraded: true,
    upgradeId: 'r_chain_kill',
    archetype: 'assassin',
    tier: 'powerful',
  },

  // ─────────────────────────────────────────────────────────────
  // POISONER ARCHETYPE CARDS (8 base + 8 upgraded)
  // Stack poison that ticks damage over time
  // ─────────────────────────────────────────────────────────────

  // Envenom
  {
    id: 'r_envenom',
    name: 'Envenom',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'poison', value: 3, target: 'enemy' }],
    description: 'Apply 3 Poison.',
    upgraded: false,
    upgradeId: 'r_envenom_plus',
    archetype: 'poisoner',
    tier: 'common',
  },
  {
    id: 'r_envenom_plus',
    name: 'Envenom+',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'poison', value: 5, target: 'enemy' }],
    description: 'Apply 5 Poison.',
    upgraded: true,
    upgradeId: 'r_envenom',
    archetype: 'poisoner',
    tier: 'common',
  },

  // Toxic Blade
  {
    id: 'r_toxic_blade',
    name: 'Toxic Blade',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 5, target: 'enemy' },
      { type: 'poison', value: 2, target: 'enemy' },
    ],
    description: 'Deal 5 damage. Apply 2 Poison.',
    upgraded: false,
    upgradeId: 'r_toxic_blade_plus',
    archetype: 'poisoner',
    tier: 'common',
  },
  {
    id: 'r_toxic_blade_plus',
    name: 'Toxic Blade+',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 8, target: 'enemy' },
      { type: 'poison', value: 3, target: 'enemy' },
    ],
    description: 'Deal 8 damage. Apply 3 Poison.',
    upgraded: true,
    upgradeId: 'r_toxic_blade',
    archetype: 'poisoner',
    tier: 'common',
  },

  // Deadly Brew
  {
    id: 'r_deadly_brew',
    name: 'Deadly Brew',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'poison', value: 4, target: 'enemy' },
      { type: 'draw', value: 1 },
    ],
    description: 'Apply 4 Poison. Draw 1 card.',
    upgraded: false,
    upgradeId: 'r_deadly_brew_plus',
    archetype: 'poisoner',
    tier: 'common',
  },
  {
    id: 'r_deadly_brew_plus',
    name: 'Deadly Brew+',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'poison', value: 6, target: 'enemy' },
      { type: 'draw', value: 1 },
    ],
    description: 'Apply 6 Poison. Draw 1 card.',
    upgraded: true,
    upgradeId: 'r_deadly_brew',
    archetype: 'poisoner',
    tier: 'common',
  },

  // Noxious Gas
  {
    id: 'r_noxious_gas',
    name: 'Noxious Gas',
    class: 'rogue',
    type: 'skill',
    cost: 2,
    effects: [{ type: 'poison', value: 8, target: 'enemy' }],
    description: 'Apply 8 Poison.',
    upgraded: false,
    upgradeId: 'r_noxious_gas_plus',
    archetype: 'poisoner',
    tier: 'powerful',
  },
  {
    id: 'r_noxious_gas_plus',
    name: 'Noxious Gas+',
    class: 'rogue',
    type: 'skill',
    cost: 2,
    effects: [{ type: 'poison', value: 12, target: 'enemy' }],
    description: 'Apply 12 Poison.',
    upgraded: true,
    upgradeId: 'r_noxious_gas',
    archetype: 'poisoner',
    tier: 'powerful',
  },

  // Venom Slash
  {
    id: 'r_venom_slash',
    name: 'Venom Slash',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 3, target: 'enemy', condition: 'per_poison' },
      { type: 'poison', value: 1, target: 'enemy' },
    ],
    description: 'Deal 3 damage per Poison on the enemy. Apply 1 Poison.',
    upgraded: false,
    upgradeId: 'r_venom_slash_plus',
    archetype: 'poisoner',
    tier: 'common',
  },
  {
    id: 'r_venom_slash_plus',
    name: 'Venom Slash+',
    class: 'rogue',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 5, target: 'enemy', condition: 'per_poison' },
      { type: 'poison', value: 2, target: 'enemy' },
    ],
    description: 'Deal 5 damage per Poison on the enemy. Apply 2 Poison.',
    upgraded: true,
    upgradeId: 'r_venom_slash',
    archetype: 'poisoner',
    tier: 'common',
  },

  // Plague
  {
    id: 'r_plague',
    name: 'Plague',
    class: 'rogue',
    type: 'skill',
    cost: 2,
    effects: [{ type: 'poison', value: 6, target: 'enemy' }],
    description: 'Apply 6 Poison.',
    upgraded: false,
    upgradeId: 'r_plague_plus',
    archetype: 'poisoner',
    tier: 'powerful',
  },
  {
    id: 'r_plague_plus',
    name: 'Plague+',
    class: 'rogue',
    type: 'skill',
    cost: 2,
    effects: [{ type: 'poison', value: 9, target: 'enemy' }],
    description: 'Apply 9 Poison.',
    upgraded: true,
    upgradeId: 'r_plague',
    archetype: 'poisoner',
    tier: 'powerful',
  },

  // Corrode
  {
    id: 'r_corrode',
    name: 'Corrode',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'poison', value: 2, target: 'enemy' },
      { type: 'debuff', value: 1, target: 'enemy', buff: 'weak' },
    ],
    description: 'Apply 2 Poison. Apply 1 Weak.',
    upgraded: false,
    upgradeId: 'r_corrode_plus',
    archetype: 'poisoner',
    tier: 'common',
  },
  {
    id: 'r_corrode_plus',
    name: 'Corrode+',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'poison', value: 3, target: 'enemy' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'weak' },
    ],
    description: 'Apply 3 Poison. Apply 2 Weak.',
    upgraded: true,
    upgradeId: 'r_corrode',
    archetype: 'poisoner',
    tier: 'common',
  },

  // Virulent Wound
  {
    id: 'r_virulent_wound',
    name: 'Virulent Wound',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 7, target: 'enemy' },
      { type: 'poison', value: 5, target: 'enemy' },
    ],
    description: 'Deal 7 damage. Apply 5 Poison.',
    upgraded: false,
    upgradeId: 'r_virulent_wound_plus',
    archetype: 'poisoner',
    tier: 'powerful',
  },
  {
    id: 'r_virulent_wound_plus',
    name: 'Virulent Wound+',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 10, target: 'enemy' },
      { type: 'poison', value: 7, target: 'enemy' },
    ],
    description: 'Deal 10 damage. Apply 7 Poison.',
    upgraded: true,
    upgradeId: 'r_virulent_wound',
    archetype: 'poisoner',
    tier: 'powerful',
  },

  // ─────────────────────────────────────────────────────────────
  // SHADOW ARCHETYPE CARDS (8 base + 8 upgraded)
  // Dodge, energy generation, card draw, and outlasting
  // ─────────────────────────────────────────────────────────────

  // Vanish
  {
    id: 'r_vanish',
    name: 'Vanish',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 7, target: 'self' },
      { type: 'energy', value: 1, target: 'self' },
    ],
    description: 'Gain 7 Block. Gain 1 Energy.',
    upgraded: false,
    upgradeId: 'r_vanish_plus',
    archetype: 'shadow',
    tier: 'common',
  },
  {
    id: 'r_vanish_plus',
    name: 'Vanish+',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 10, target: 'self' },
      { type: 'energy', value: 1, target: 'self' },
    ],
    description: 'Gain 10 Block. Gain 1 Energy.',
    upgraded: true,
    upgradeId: 'r_vanish',
    archetype: 'shadow',
    tier: 'common',
  },

  // Cloak of Shadows
  {
    id: 'r_cloak_of_shadows',
    name: 'Cloak of Shadows',
    class: 'rogue',
    type: 'skill',
    cost: 2,
    effects: [{ type: 'block', value: 14, target: 'self' }],
    description: 'Gain 14 Block.',
    upgraded: false,
    upgradeId: 'r_cloak_of_shadows_plus',
    archetype: 'shadow',
    tier: 'powerful',
  },
  {
    id: 'r_cloak_of_shadows_plus',
    name: 'Cloak of Shadows+',
    class: 'rogue',
    type: 'skill',
    cost: 2,
    effects: [{ type: 'block', value: 20, target: 'self' }],
    description: 'Gain 20 Block.',
    upgraded: true,
    upgradeId: 'r_cloak_of_shadows',
    archetype: 'shadow',
    tier: 'powerful',
  },

  // Shadowstep
  {
    id: 'r_shadowstep',
    name: 'Shadowstep',
    class: 'rogue',
    type: 'skill',
    cost: 0,
    effects: [
      { type: 'energy', value: 1, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 1 Energy. Draw 1 card.',
    upgraded: false,
    upgradeId: 'r_shadowstep_plus',
    archetype: 'shadow',
    tier: 'common',
  },
  {
    id: 'r_shadowstep_plus',
    name: 'Shadowstep+',
    class: 'rogue',
    type: 'skill',
    cost: 0,
    effects: [
      { type: 'energy', value: 2, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 2 Energy. Draw 1 card.',
    upgraded: true,
    upgradeId: 'r_shadowstep',
    archetype: 'shadow',
    tier: 'common',
  },

  // Evasion
  {
    id: 'r_evasion',
    name: 'Evasion',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 9, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 9 Block. Draw 1 card.',
    upgraded: false,
    upgradeId: 'r_evasion_plus',
    archetype: 'shadow',
    tier: 'common',
  },
  {
    id: 'r_evasion_plus',
    name: 'Evasion+',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 13, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 13 Block. Draw 1 card.',
    upgraded: true,
    upgradeId: 'r_evasion',
    archetype: 'shadow',
    tier: 'common',
  },

  // Blade Dance
  {
    id: 'r_blade_dance',
    name: 'Blade Dance',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'aoe_damage', value: 6 },
      { type: 'block', value: 6, target: 'self' },
    ],
    description: 'Deal 6 damage to all enemies. Gain 6 Block.',
    upgraded: false,
    upgradeId: 'r_blade_dance_plus',
    archetype: 'shadow',
    tier: 'powerful',
  },
  {
    id: 'r_blade_dance_plus',
    name: 'Blade Dance+',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'aoe_damage', value: 9 },
      { type: 'block', value: 9, target: 'self' },
    ],
    description: 'Deal 9 damage to all enemies. Gain 9 Block.',
    upgraded: true,
    upgradeId: 'r_blade_dance',
    archetype: 'shadow',
    tier: 'powerful',
  },

  // Sleight of Hand
  {
    id: 'r_sleight_of_hand',
    name: 'Sleight of Hand',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'draw', value: 2 },
      { type: 'energy', value: 1, target: 'self' },
    ],
    description: 'Draw 2 cards. Gain 1 Energy.',
    upgraded: false,
    upgradeId: 'r_sleight_of_hand_plus',
    archetype: 'shadow',
    tier: 'common',
  },
  {
    id: 'r_sleight_of_hand_plus',
    name: 'Sleight of Hand+',
    class: 'rogue',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'draw', value: 3 },
      { type: 'energy', value: 1, target: 'self' },
    ],
    description: 'Draw 3 cards. Gain 1 Energy.',
    upgraded: true,
    upgradeId: 'r_sleight_of_hand',
    archetype: 'shadow',
    tier: 'common',
  },

  // Tumble
  {
    id: 'r_tumble',
    name: 'Tumble',
    class: 'rogue',
    type: 'skill',
    cost: 0,
    effects: [{ type: 'block', value: 5, target: 'self' }],
    description: 'Gain 5 Block.',
    upgraded: false,
    upgradeId: 'r_tumble_plus',
    archetype: 'shadow',
    tier: 'common',
  },
  {
    id: 'r_tumble_plus',
    name: 'Tumble+',
    class: 'rogue',
    type: 'skill',
    cost: 0,
    effects: [
      { type: 'block', value: 5, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 5 Block. Draw 1 card.',
    upgraded: true,
    upgradeId: 'r_tumble',
    archetype: 'shadow',
    tier: 'common',
  },

  // Phantom Strike
  {
    id: 'r_phantom_strike',
    name: 'Phantom Strike',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 12, target: 'enemy' },
      { type: 'block', value: 8, target: 'self' },
    ],
    description: 'Deal 12 damage. Gain 8 Block.',
    upgraded: false,
    upgradeId: 'r_phantom_strike_plus',
    archetype: 'shadow',
    tier: 'powerful',
  },
  {
    id: 'r_phantom_strike_plus',
    name: 'Phantom Strike+',
    class: 'rogue',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 17, target: 'enemy' },
      { type: 'block', value: 12, target: 'self' },
    ],
    description: 'Deal 17 damage. Gain 12 Block.',
    upgraded: true,
    upgradeId: 'r_phantom_strike',
    archetype: 'shadow',
    tier: 'powerful',
  },
];
