import type { CardDefinition } from './types';

export const WARRIOR_CARDS: CardDefinition[] = [
  // ─────────────────────────────────────────────
  // BASIC CARDS
  // ─────────────────────────────────────────────

  // Strike
  {
    id: 'w_strike',
    name: 'Strike',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [{ type: 'damage', value: 6, target: 'enemy' }],
    description: 'Deal 6 damage.',
    upgraded: false,
    upgradeId: 'w_strike_plus',
    tier: 'basic',
  },
  {
    id: 'w_strike_plus',
    name: 'Strike',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [{ type: 'damage', value: 9, target: 'enemy' }],
    description: 'Deal 9 damage.',
    upgraded: true,
    upgradeId: 'w_strike',
    tier: 'basic',
  },

  // Defend
  {
    id: 'w_defend',
    name: 'Defend',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'block', value: 5, target: 'self' }],
    description: 'Gain 5 Block.',
    upgraded: false,
    upgradeId: 'w_defend_plus',
    tier: 'basic',
  },
  {
    id: 'w_defend_plus',
    name: 'Defend',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'block', value: 8, target: 'self' }],
    description: 'Gain 8 Block.',
    upgraded: true,
    upgradeId: 'w_defend',
    tier: 'basic',
  },

  // Bash
  {
    id: 'w_bash',
    name: 'Bash',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 8, target: 'enemy' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Deal 8 damage. Apply 2 Vulnerable.',
    upgraded: false,
    upgradeId: 'w_bash_plus',
    tier: 'basic',
  },
  {
    id: 'w_bash_plus',
    name: 'Bash',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 12, target: 'enemy' },
      { type: 'debuff', value: 3, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Deal 12 damage. Apply 3 Vulnerable.',
    upgraded: true,
    upgradeId: 'w_bash',
    tier: 'basic',
  },

  // Heavy Blow
  {
    id: 'w_heavy_blow',
    name: 'Heavy Blow',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [{ type: 'damage', value: 12, target: 'enemy' }],
    description: 'Deal 12 damage.',
    upgraded: false,
    upgradeId: 'w_heavy_blow_plus',
    tier: 'basic',
  },
  {
    id: 'w_heavy_blow_plus',
    name: 'Heavy Blow',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [{ type: 'damage', value: 18, target: 'enemy' }],
    description: 'Deal 18 damage.',
    upgraded: true,
    upgradeId: 'w_heavy_blow',
    tier: 'basic',
  },

  // War Cry
  {
    id: 'w_war_cry',
    name: 'War Cry',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'draw', value: 2 }],
    description: 'Draw 2 cards.',
    upgraded: false,
    upgradeId: 'w_war_cry_plus',
    tier: 'basic',
  },
  {
    id: 'w_war_cry_plus',
    name: 'War Cry',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'draw', value: 3 }],
    description: 'Draw 3 cards.',
    upgraded: true,
    upgradeId: 'w_war_cry',
    tier: 'basic',
  },

  // Shield Bash
  {
    id: 'w_shield_bash',
    name: 'Shield Bash',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 5, target: 'enemy' },
      { type: 'block', value: 5, target: 'self' },
    ],
    description: 'Deal 5 damage. Gain 5 Block.',
    upgraded: false,
    upgradeId: 'w_shield_bash_plus',
    tier: 'basic',
  },
  {
    id: 'w_shield_bash_plus',
    name: 'Shield Bash',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 8, target: 'enemy' },
      { type: 'block', value: 8, target: 'self' },
    ],
    description: 'Deal 8 damage. Gain 8 Block.',
    upgraded: true,
    upgradeId: 'w_shield_bash',
    tier: 'basic',
  },

  // Cleave
  {
    id: 'w_cleave',
    name: 'Cleave',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [{ type: 'aoe_damage', value: 8 }],
    description: 'Deal 8 damage to all enemies.',
    upgraded: false,
    upgradeId: 'w_cleave_plus',
    tier: 'basic',
  },
  {
    id: 'w_cleave_plus',
    name: 'Cleave',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [{ type: 'aoe_damage', value: 12 }],
    description: 'Deal 12 damage to all enemies.',
    upgraded: true,
    upgradeId: 'w_cleave',
    tier: 'basic',
  },

  // Intimidate
  {
    id: 'w_intimidate',
    name: 'Intimidate',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'debuff', value: 1, target: 'enemy', buff: 'weak' }],
    description: 'Apply 1 Weak to the enemy.',
    upgraded: false,
    upgradeId: 'w_intimidate_plus',
    tier: 'basic',
  },
  {
    id: 'w_intimidate_plus',
    name: 'Intimidate',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [{ type: 'debuff', value: 2, target: 'enemy', buff: 'weak' }],
    description: 'Apply 2 Weak to the enemy.',
    upgraded: true,
    upgradeId: 'w_intimidate',
    tier: 'basic',
  },

  // Whirlwind
  {
    id: 'w_whirlwind',
    name: 'Whirlwind',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [{ type: 'aoe_damage', value: 5 }],
    description: 'Deal 5 damage to all enemies.',
    upgraded: false,
    upgradeId: 'w_whirlwind_plus',
    tier: 'basic',
  },
  {
    id: 'w_whirlwind_plus',
    name: 'Whirlwind',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [{ type: 'aoe_damage', value: 8 }],
    description: 'Deal 8 damage to all enemies.',
    upgraded: true,
    upgradeId: 'w_whirlwind',
    tier: 'basic',
  },

  // Pummel
  {
    id: 'w_pummel',
    name: 'Pummel',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 4, target: 'enemy' },
      { type: 'damage', value: 4, target: 'enemy' },
    ],
    description: 'Deal 4 damage twice.',
    upgraded: false,
    upgradeId: 'w_pummel_plus',
    tier: 'basic',
  },
  {
    id: 'w_pummel_plus',
    name: 'Pummel',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 4, target: 'enemy' },
      { type: 'damage', value: 4, target: 'enemy' },
      { type: 'damage', value: 4, target: 'enemy' },
    ],
    description: 'Deal 4 damage 3 times.',
    upgraded: true,
    upgradeId: 'w_pummel',
    tier: 'basic',
  },

  // Body Slam
  {
    id: 'w_body_slam',
    name: 'Body Slam',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [{ type: 'damage', value: 8, target: 'enemy' }],
    description: 'Deal 8 damage.',
    upgraded: false,
    upgradeId: 'w_body_slam_plus',
    tier: 'basic',
  },
  {
    id: 'w_body_slam_plus',
    name: 'Body Slam',
    class: 'warrior',
    type: 'attack',
    cost: 0,
    effects: [{ type: 'damage', value: 8, target: 'enemy' }],
    description: 'Deal 8 damage.',
    upgraded: true,
    upgradeId: 'w_body_slam',
    tier: 'basic',
  },

  // Shrug It Off
  {
    id: 'w_shrug_it_off',
    name: 'Shrug It Off',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 8, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 8 Block. Draw 1 card.',
    upgraded: false,
    upgradeId: 'w_shrug_it_off_plus',
    tier: 'basic',
  },
  {
    id: 'w_shrug_it_off_plus',
    name: 'Shrug It Off',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 11, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 11 Block. Draw 1 card.',
    upgraded: true,
    upgradeId: 'w_shrug_it_off',
    tier: 'basic',
  },

  // Flex
  {
    id: 'w_flex',
    name: 'Flex',
    class: 'warrior',
    type: 'skill',
    cost: 0,
    effects: [{ type: 'buff', value: 2, target: 'self', buff: 'strength' }],
    description: 'Gain 2 Strength.',
    upgraded: false,
    upgradeId: 'w_flex_plus',
    tier: 'basic',
  },
  {
    id: 'w_flex_plus',
    name: 'Flex',
    class: 'warrior',
    type: 'skill',
    cost: 0,
    effects: [{ type: 'buff', value: 4, target: 'self', buff: 'strength' }],
    description: 'Gain 4 Strength.',
    upgraded: true,
    upgradeId: 'w_flex',
    tier: 'basic',
  },

  // Bloodletting
  {
    id: 'w_bloodletting',
    name: 'Bloodletting',
    class: 'warrior',
    type: 'skill',
    cost: 0,
    effects: [
      { type: 'damage', value: 3, target: 'self' },
      { type: 'energy', value: 2, target: 'self' },
    ],
    description: 'Lose 3 HP. Gain 2 Energy.',
    upgraded: false,
    upgradeId: 'w_bloodletting_plus',
    tier: 'basic',
  },
  {
    id: 'w_bloodletting_plus',
    name: 'Bloodletting',
    class: 'warrior',
    type: 'skill',
    cost: 0,
    effects: [
      { type: 'damage', value: 3, target: 'self' },
      { type: 'energy', value: 3, target: 'self' },
    ],
    description: 'Lose 3 HP. Gain 3 Energy.',
    upgraded: true,
    upgradeId: 'w_bloodletting',
    tier: 'basic',
  },

  // True Grit
  {
    id: 'w_true_grit',
    name: 'True Grit',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 7, target: 'self' },
      { type: 'buff', value: 1, target: 'self', buff: 'strength' },
    ],
    description: 'Gain 7 Block. Gain 1 Strength.',
    upgraded: false,
    upgradeId: 'w_true_grit_plus',
    tier: 'basic',
  },
  {
    id: 'w_true_grit_plus',
    name: 'True Grit',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 9, target: 'self' },
      { type: 'buff', value: 2, target: 'self', buff: 'strength' },
    ],
    description: 'Gain 9 Block. Gain 2 Strength.',
    upgraded: true,
    upgradeId: 'w_true_grit',
    tier: 'basic',
  },

  // Iron Will
  {
    id: 'w_iron_will',
    name: 'Iron Will',
    class: 'warrior',
    type: 'power',
    cost: 1,
    effects: [{ type: 'buff', value: 1, target: 'self', buff: 'strength' }],
    description: 'Gain 1 Strength.',
    upgraded: false,
    upgradeId: 'w_iron_will_plus',
    tier: 'basic',
  },
  {
    id: 'w_iron_will_plus',
    name: 'Iron Will',
    class: 'warrior',
    type: 'power',
    cost: 1,
    effects: [{ type: 'buff', value: 2, target: 'self', buff: 'strength' }],
    description: 'Gain 2 Strength.',
    upgraded: true,
    upgradeId: 'w_iron_will',
    tier: 'basic',
  },

  // ─────────────────────────────────────────────
  // BERSERKER ARCHETYPE CARDS
  // ─────────────────────────────────────────────

  // Reckless Swing
  {
    id: 'w_reckless_swing',
    name: 'Reckless Swing',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 14, target: 'enemy' },
      { type: 'damage', value: 4, target: 'self' },
    ],
    description: 'Deal 14 damage. Take 4 damage.',
    upgraded: false,
    upgradeId: 'w_reckless_swing_plus',
    archetype: 'berserker',
    tier: 'common',
  },
  {
    id: 'w_reckless_swing_plus',
    name: 'Reckless Swing',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 20, target: 'enemy' },
      { type: 'damage', value: 4, target: 'self' },
    ],
    description: 'Deal 20 damage. Take 4 damage.',
    upgraded: true,
    upgradeId: 'w_reckless_swing',
    archetype: 'berserker',
    tier: 'common',
  },

  // Blood Fury
  {
    id: 'w_blood_fury',
    name: 'Blood Fury',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 3, target: 'enemy', condition: 'per_missing_hp' },
    ],
    description: 'Deal 3 damage for each missing HP.',
    upgraded: false,
    upgradeId: 'w_blood_fury_plus',
    archetype: 'berserker',
    tier: 'powerful',
  },
  {
    id: 'w_blood_fury_plus',
    name: 'Blood Fury',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 5, target: 'enemy', condition: 'per_missing_hp' },
    ],
    description: 'Deal 5 damage for each missing HP.',
    upgraded: true,
    upgradeId: 'w_blood_fury',
    archetype: 'berserker',
    tier: 'powerful',
  },

  // Rage Stack
  {
    id: 'w_rage_stack',
    name: 'Rage Stack',
    class: 'warrior',
    type: 'skill',
    cost: 0,
    effects: [
      { type: 'buff', value: 1, target: 'self', buff: 'rage' },
    ],
    description: 'Gain 1 Rage.',
    upgraded: false,
    upgradeId: 'w_rage_stack_plus',
    archetype: 'berserker',
    tier: 'common',
  },
  {
    id: 'w_rage_stack_plus',
    name: 'Rage Stack',
    class: 'warrior',
    type: 'skill',
    cost: 0,
    effects: [
      { type: 'buff', value: 2, target: 'self', buff: 'rage' },
    ],
    description: 'Gain 2 Rage.',
    upgraded: true,
    upgradeId: 'w_rage_stack',
    archetype: 'berserker',
    tier: 'common',
  },

  // Seeing Red
  {
    id: 'w_seeing_red',
    name: 'Seeing Red',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'energy', value: 2, target: 'self' },
      { type: 'buff', value: 1, target: 'self', buff: 'rage' },
    ],
    description: 'Gain 2 Energy. Gain 1 Rage.',
    upgraded: false,
    upgradeId: 'w_seeing_red_plus',
    archetype: 'berserker',
    tier: 'powerful',
  },
  {
    id: 'w_seeing_red_plus',
    name: 'Seeing Red',
    class: 'warrior',
    type: 'skill',
    cost: 0,
    effects: [
      { type: 'energy', value: 2, target: 'self' },
      { type: 'buff', value: 1, target: 'self', buff: 'rage' },
    ],
    description: 'Gain 2 Energy. Gain 1 Rage.',
    upgraded: true,
    upgradeId: 'w_seeing_red',
    archetype: 'berserker',
    tier: 'powerful',
  },

  // Frenzy
  {
    id: 'w_frenzy',
    name: 'Frenzy',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 7, target: 'enemy' },
      { type: 'damage', value: 7, target: 'enemy' },
      { type: 'buff', value: 1, target: 'self', buff: 'rage' },
    ],
    description: 'Deal 7 damage twice. Gain 1 Rage.',
    upgraded: false,
    upgradeId: 'w_frenzy_plus',
    archetype: 'berserker',
    tier: 'common',
  },
  {
    id: 'w_frenzy_plus',
    name: 'Frenzy',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 10, target: 'enemy' },
      { type: 'damage', value: 10, target: 'enemy' },
      { type: 'buff', value: 1, target: 'self', buff: 'rage' },
    ],
    description: 'Deal 10 damage twice. Gain 1 Rage.',
    upgraded: true,
    upgradeId: 'w_frenzy',
    archetype: 'berserker',
    tier: 'common',
  },

  // Wound Exploit
  {
    id: 'w_wound_exploit',
    name: 'Wound Exploit',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 8, target: 'enemy' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Deal 8 damage. Apply 2 Vulnerable.',
    upgraded: false,
    upgradeId: 'w_wound_exploit_plus',
    archetype: 'berserker',
    tier: 'common',
  },
  {
    id: 'w_wound_exploit_plus',
    name: 'Wound Exploit',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 12, target: 'enemy' },
      { type: 'debuff', value: 3, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Deal 12 damage. Apply 3 Vulnerable.',
    upgraded: true,
    upgradeId: 'w_wound_exploit',
    archetype: 'berserker',
    tier: 'common',
  },

  // Berserk
  {
    id: 'w_berserk',
    name: 'Berserk',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 2, target: 'enemy', condition: 'per_missing_hp' },
      { type: 'buff', value: 2, target: 'self', buff: 'rage' },
    ],
    description: 'Deal 2 damage per missing HP. Gain 2 Rage.',
    upgraded: false,
    upgradeId: 'w_berserk_plus',
    archetype: 'berserker',
    tier: 'powerful',
  },
  {
    id: 'w_berserk_plus',
    name: 'Berserk',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 3, target: 'enemy', condition: 'per_missing_hp' },
      { type: 'buff', value: 3, target: 'self', buff: 'rage' },
    ],
    description: 'Deal 3 damage per missing HP. Gain 3 Rage.',
    upgraded: true,
    upgradeId: 'w_berserk',
    archetype: 'berserker',
    tier: 'powerful',
  },

  // Rampage
  {
    id: 'w_rampage',
    name: 'Rampage',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 10, target: 'enemy' },
      { type: 'buff', value: 3, target: 'self', buff: 'strength' },
    ],
    description: 'Deal 10 damage. Gain 3 Strength.',
    upgraded: false,
    upgradeId: 'w_rampage_plus',
    archetype: 'berserker',
    tier: 'powerful',
  },
  {
    id: 'w_rampage_plus',
    name: 'Rampage',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 15, target: 'enemy' },
      { type: 'buff', value: 5, target: 'self', buff: 'strength' },
    ],
    description: 'Deal 15 damage. Gain 5 Strength.',
    upgraded: true,
    upgradeId: 'w_rampage',
    archetype: 'berserker',
    tier: 'powerful',
  },

  // ─────────────────────────────────────────────
  // IRONCLAD ARCHETYPE CARDS
  // ─────────────────────────────────────────────

  // Fortress
  {
    id: 'w_fortress',
    name: 'Fortress',
    class: 'warrior',
    type: 'skill',
    cost: 2,
    effects: [
      { type: 'block', value: 15, target: 'self' },
      { type: 'buff', value: 1, target: 'self', buff: 'barricade' },
    ],
    description: 'Gain 15 Block. Gain 1 Barricade.',
    upgraded: false,
    upgradeId: 'w_fortress_plus',
    archetype: 'ironclad',
    tier: 'common',
  },
  {
    id: 'w_fortress_plus',
    name: 'Fortress',
    class: 'warrior',
    type: 'skill',
    cost: 2,
    effects: [
      { type: 'block', value: 22, target: 'self' },
      { type: 'buff', value: 2, target: 'self', buff: 'barricade' },
    ],
    description: 'Gain 22 Block. Gain 2 Barricade.',
    upgraded: true,
    upgradeId: 'w_fortress',
    archetype: 'ironclad',
    tier: 'common',
  },

  // Iron Skin
  {
    id: 'w_iron_skin',
    name: 'Iron Skin',
    class: 'warrior',
    type: 'power',
    cost: 1,
    effects: [
      { type: 'buff', value: 2, target: 'self', buff: 'thorns' },
    ],
    description: 'Gain 2 Thorns.',
    upgraded: false,
    upgradeId: 'w_iron_skin_plus',
    archetype: 'ironclad',
    tier: 'common',
  },
  {
    id: 'w_iron_skin_plus',
    name: 'Iron Skin',
    class: 'warrior',
    type: 'power',
    cost: 1,
    effects: [
      { type: 'buff', value: 4, target: 'self', buff: 'thorns' },
    ],
    description: 'Gain 4 Thorns.',
    upgraded: true,
    upgradeId: 'w_iron_skin',
    archetype: 'ironclad',
    tier: 'common',
  },

  // Barricade
  {
    id: 'w_barricade',
    name: 'Barricade',
    class: 'warrior',
    type: 'power',
    cost: 3,
    effects: [
      { type: 'buff', value: 1, target: 'self', buff: 'barricade' },
      { type: 'block', value: 8, target: 'self' },
    ],
    description: 'Your Block no longer expires. Gain 8 Block.',
    upgraded: false,
    upgradeId: 'w_barricade_plus',
    archetype: 'ironclad',
    tier: 'powerful',
  },
  {
    id: 'w_barricade_plus',
    name: 'Barricade',
    class: 'warrior',
    type: 'power',
    cost: 2,
    effects: [
      { type: 'buff', value: 1, target: 'self', buff: 'barricade' },
      { type: 'block', value: 8, target: 'self' },
    ],
    description: 'Your Block no longer expires. Gain 8 Block.',
    upgraded: true,
    upgradeId: 'w_barricade',
    archetype: 'ironclad',
    tier: 'powerful',
  },

  // Thorns
  {
    id: 'w_thorns',
    name: 'Thorns',
    class: 'warrior',
    type: 'power',
    cost: 2,
    effects: [
      { type: 'buff', value: 3, target: 'self', buff: 'thorns' },
      { type: 'block', value: 5, target: 'self' },
    ],
    description: 'Gain 3 Thorns. Gain 5 Block.',
    upgraded: false,
    upgradeId: 'w_thorns_plus',
    archetype: 'ironclad',
    tier: 'common',
  },
  {
    id: 'w_thorns_plus',
    name: 'Thorns',
    class: 'warrior',
    type: 'power',
    cost: 2,
    effects: [
      { type: 'buff', value: 5, target: 'self', buff: 'thorns' },
      { type: 'block', value: 8, target: 'self' },
    ],
    description: 'Gain 5 Thorns. Gain 8 Block.',
    upgraded: true,
    upgradeId: 'w_thorns',
    archetype: 'ironclad',
    tier: 'common',
  },

  // Counter Blow
  {
    id: 'w_counter_blow',
    name: 'Counter Blow',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 7, target: 'enemy' },
      { type: 'block', value: 7, target: 'self' },
      { type: 'buff', value: 1, target: 'self', buff: 'thorns' },
    ],
    description: 'Deal 7 damage. Gain 7 Block. Gain 1 Thorns.',
    upgraded: false,
    upgradeId: 'w_counter_blow_plus',
    archetype: 'ironclad',
    tier: 'common',
  },
  {
    id: 'w_counter_blow_plus',
    name: 'Counter Blow',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 10, target: 'enemy' },
      { type: 'block', value: 10, target: 'self' },
      { type: 'buff', value: 2, target: 'self', buff: 'thorns' },
    ],
    description: 'Deal 10 damage. Gain 10 Block. Gain 2 Thorns.',
    upgraded: true,
    upgradeId: 'w_counter_blow',
    archetype: 'ironclad',
    tier: 'common',
  },

  // Entrench
  {
    id: 'w_entrench',
    name: 'Entrench',
    class: 'warrior',
    type: 'skill',
    cost: 2,
    effects: [
      { type: 'block', value: 12, target: 'self' },
      { type: 'block', value: 12, target: 'self' },
    ],
    description: 'Double your current Block. Gain 12 Block.',
    upgraded: false,
    upgradeId: 'w_entrench_plus',
    archetype: 'ironclad',
    tier: 'powerful',
  },
  {
    id: 'w_entrench_plus',
    name: 'Entrench',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 12, target: 'self' },
      { type: 'block', value: 12, target: 'self' },
    ],
    description: 'Double your current Block. Gain 12 Block.',
    upgraded: true,
    upgradeId: 'w_entrench',
    archetype: 'ironclad',
    tier: 'powerful',
  },

  // Shield Wall
  {
    id: 'w_shield_wall',
    name: 'Shield Wall',
    class: 'warrior',
    type: 'skill',
    cost: 2,
    effects: [
      { type: 'block', value: 20, target: 'self' },
    ],
    description: 'Gain 20 Block.',
    upgraded: false,
    upgradeId: 'w_shield_wall_plus',
    archetype: 'ironclad',
    tier: 'common',
  },
  {
    id: 'w_shield_wall_plus',
    name: 'Shield Wall',
    class: 'warrior',
    type: 'skill',
    cost: 2,
    effects: [
      { type: 'block', value: 30, target: 'self' },
    ],
    description: 'Gain 30 Block.',
    upgraded: true,
    upgradeId: 'w_shield_wall',
    archetype: 'ironclad',
    tier: 'common',
  },

  // Armor Up
  {
    id: 'w_armor_up',
    name: 'Armor Up',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 10, target: 'self' },
      { type: 'buff', value: 1, target: 'self', buff: 'thorns' },
    ],
    description: 'Gain 10 Block. Gain 1 Thorns.',
    upgraded: false,
    upgradeId: 'w_armor_up_plus',
    archetype: 'ironclad',
    tier: 'common',
  },
  {
    id: 'w_armor_up_plus',
    name: 'Armor Up',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 14, target: 'self' },
      { type: 'buff', value: 2, target: 'self', buff: 'thorns' },
    ],
    description: 'Gain 14 Block. Gain 2 Thorns.',
    upgraded: true,
    upgradeId: 'w_armor_up',
    archetype: 'ironclad',
    tier: 'common',
  },

  // ─────────────────────────────────────────────
  // WARLORD ARCHETYPE CARDS
  // ─────────────────────────────────────────────

  // Battle Shout
  {
    id: 'w_battle_shout',
    name: 'Battle Shout',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'buff', value: 2, target: 'self', buff: 'strength' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 2 Strength. Draw 1 card.',
    upgraded: false,
    upgradeId: 'w_battle_shout_plus',
    archetype: 'warlord',
    tier: 'common',
  },
  {
    id: 'w_battle_shout_plus',
    name: 'Battle Shout',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'buff', value: 3, target: 'self', buff: 'strength' },
      { type: 'draw', value: 2 },
    ],
    description: 'Gain 3 Strength. Draw 2 cards.',
    upgraded: true,
    upgradeId: 'w_battle_shout',
    archetype: 'warlord',
    tier: 'common',
  },

  // Weaken
  {
    id: 'w_weaken',
    name: 'Weaken',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'debuff', value: 2, target: 'enemy', buff: 'weak' },
    ],
    description: 'Apply 2 Weak to the enemy.',
    upgraded: false,
    upgradeId: 'w_weaken_plus',
    archetype: 'warlord',
    tier: 'common',
  },
  {
    id: 'w_weaken_plus',
    name: 'Weaken',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'debuff', value: 3, target: 'enemy', buff: 'weak' },
    ],
    description: 'Apply 3 Weak to the enemy.',
    upgraded: true,
    upgradeId: 'w_weaken',
    archetype: 'warlord',
    tier: 'common',
  },

  // Disarm
  {
    id: 'w_disarm',
    name: 'Disarm',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'debuff', value: 2, target: 'enemy', buff: 'weak' },
      { type: 'debuff', value: 1, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Apply 2 Weak and 1 Vulnerable to the enemy.',
    upgraded: false,
    upgradeId: 'w_disarm_plus',
    archetype: 'warlord',
    tier: 'common',
  },
  {
    id: 'w_disarm_plus',
    name: 'Disarm',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'debuff', value: 3, target: 'enemy', buff: 'weak' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Apply 3 Weak and 2 Vulnerable to the enemy.',
    upgraded: true,
    upgradeId: 'w_disarm',
    archetype: 'warlord',
    tier: 'common',
  },

  // Commanding Strike
  {
    id: 'w_commanding_strike',
    name: 'Commanding Strike',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 10, target: 'enemy' },
      { type: 'buff', value: 2, target: 'self', buff: 'strength' },
    ],
    description: 'Deal 10 damage. Gain 2 Strength.',
    upgraded: false,
    upgradeId: 'w_commanding_strike_plus',
    archetype: 'warlord',
    tier: 'powerful',
  },
  {
    id: 'w_commanding_strike_plus',
    name: 'Commanding Strike',
    class: 'warrior',
    type: 'attack',
    cost: 2,
    effects: [
      { type: 'damage', value: 15, target: 'enemy' },
      { type: 'buff', value: 3, target: 'self', buff: 'strength' },
    ],
    description: 'Deal 15 damage. Gain 3 Strength.',
    upgraded: true,
    upgradeId: 'w_commanding_strike',
    archetype: 'warlord',
    tier: 'powerful',
  },

  // Rally
  {
    id: 'w_rally',
    name: 'Rally',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'draw', value: 2 },
      { type: 'heal', value: 3, target: 'self' },
    ],
    description: 'Draw 2 cards. Heal 3 HP.',
    upgraded: false,
    upgradeId: 'w_rally_plus',
    archetype: 'warlord',
    tier: 'common',
  },
  {
    id: 'w_rally_plus',
    name: 'Rally',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'draw', value: 3 },
      { type: 'heal', value: 5, target: 'self' },
    ],
    description: 'Draw 3 cards. Heal 5 HP.',
    upgraded: true,
    upgradeId: 'w_rally',
    archetype: 'warlord',
    tier: 'common',
  },

  // Tactical Retreat
  {
    id: 'w_tactical_retreat',
    name: 'Tactical Retreat',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 8, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    description: 'Gain 8 Block. Draw 1 card.',
    upgraded: false,
    upgradeId: 'w_tactical_retreat_plus',
    archetype: 'warlord',
    tier: 'common',
  },
  {
    id: 'w_tactical_retreat_plus',
    name: 'Tactical Retreat',
    class: 'warrior',
    type: 'skill',
    cost: 1,
    effects: [
      { type: 'block', value: 12, target: 'self' },
      { type: 'draw', value: 2 },
    ],
    description: 'Gain 12 Block. Draw 2 cards.',
    upgraded: true,
    upgradeId: 'w_tactical_retreat',
    archetype: 'warlord',
    tier: 'common',
  },

  // Overwhelm
  {
    id: 'w_overwhelm',
    name: 'Overwhelm',
    class: 'warrior',
    type: 'attack',
    cost: 3,
    effects: [
      { type: 'aoe_damage', value: 12 },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'weak' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Deal 12 damage to all enemies. Apply 2 Weak and 2 Vulnerable.',
    upgraded: false,
    upgradeId: 'w_overwhelm_plus',
    archetype: 'warlord',
    tier: 'powerful',
  },
  {
    id: 'w_overwhelm_plus',
    name: 'Overwhelm',
    class: 'warrior',
    type: 'attack',
    cost: 3,
    effects: [
      { type: 'aoe_damage', value: 18 },
      { type: 'debuff', value: 3, target: 'enemy', buff: 'weak' },
      { type: 'debuff', value: 3, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Deal 18 damage to all enemies. Apply 3 Weak and 3 Vulnerable.',
    upgraded: true,
    upgradeId: 'w_overwhelm',
    archetype: 'warlord',
    tier: 'powerful',
  },

  // Exploit Opening
  {
    id: 'w_exploit_opening',
    name: 'Exploit Opening',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 9, target: 'enemy' },
      { type: 'debuff', value: 1, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Deal 9 damage. Apply 1 Vulnerable.',
    upgraded: false,
    upgradeId: 'w_exploit_opening_plus',
    archetype: 'warlord',
    tier: 'common',
  },
  {
    id: 'w_exploit_opening_plus',
    name: 'Exploit Opening',
    class: 'warrior',
    type: 'attack',
    cost: 1,
    effects: [
      { type: 'damage', value: 14, target: 'enemy' },
      { type: 'debuff', value: 2, target: 'enemy', buff: 'vulnerable' },
    ],
    description: 'Deal 14 damage. Apply 2 Vulnerable.',
    upgraded: true,
    upgradeId: 'w_exploit_opening',
    archetype: 'warlord',
    tier: 'common',
  },
];
